# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0003_auto_20181019_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
