# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0003_auto_20181022_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
