# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0005_auto_20181019_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
