# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0006_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='biz',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
