# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0007_auto_20181020_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
