# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0008_neighbourhood_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
