# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0010_auto_20181021_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
